<?php
declare(strict_types=1);
namespace Sif\Tests\Foundation\Unit\Security;
use DateTimeImmutable; use PHPUnit\Framework\TestCase; use Sif\Foundation\Security\Contracts\CredentialTrustAnchorPolicyInterface; use Sif\Foundation\Security\Contracts\CredentialTrustAnchorResolverInterface; use Sif\Foundation\Security\Contracts\CredentialTrustKeyLifecyclePolicyInterface; use Sif\Foundation\Security\Contracts\CredentialTrustKeyMaterialResolverInterface; use Sif\Foundation\Security\VerifiableCredentials\Trust\Anchors\CredentialTrustAnchor; use Sif\Foundation\Security\VerifiableCredentials\Trust\Anchors\CredentialTrustAnchorStatus; use Sif\Foundation\Security\VerifiableCredentials\Trust\CredentialTrustEntityReference; use Sif\Foundation\Security\VerifiableCredentials\Trust\CredentialTrustEntityRole; use Sif\Foundation\Security\VerifiableCredentials\Trust\Keys\CredentialTrustKeyLifecycleTransition; use Sif\Foundation\Security\VerifiableCredentials\Trust\Keys\CredentialTrustKeyMaterial; use Sif\Foundation\Security\VerifiableCredentials\Trust\Keys\CredentialTrustKeyMaterialStatus;
final class CredentialTrustAnchorsAndKeyMaterialLifecycleBoundariesTest extends TestCase {
private function anchorEntity():CredentialTrustEntityReference{return new CredentialTrustEntityReference('https://trust-anchor.example.test',CredentialTrustEntityRole::TrustAnchor,'ecosystem-alpha');}
public function testTrustAnchorStatesAreExplicit():void{self::assertSame('active',CredentialTrustAnchorStatus::Active->value);self::assertSame('suspended',CredentialTrustAnchorStatus::Suspended->value);self::assertSame('retired',CredentialTrustAnchorStatus::Retired->value);self::assertSame('revoked',CredentialTrustAnchorStatus::Revoked->value);}
public function testTrustAnchorKeepsIdentityValidityAndKeyReferencesExplicit():void{$a=new CredentialTrustAnchor('anchor-001',$this->anchorEntity(),CredentialTrustAnchorStatus::Active,new DateTimeImmutable('2026-01-01T00:00:00Z'),new DateTimeImmutable('2030-01-01T00:00:00Z'),['key-001','key-002'],['source'=>'governed-trust-store']);self::assertSame('anchor-001',$a->anchorId());self::assertSame(CredentialTrustAnchorStatus::Active,$a->status());self::assertSame(['key-001','key-002'],$a->keyMaterialIds());self::assertSame('governed-trust-store',$a->metadata()['source']);}
public function testKeyMaterialStatesAreExplicit():void{self::assertSame('active',CredentialTrustKeyMaterialStatus::Active->value);self::assertSame('rotating',CredentialTrustKeyMaterialStatus::Rotating->value);self::assertSame('retired',CredentialTrustKeyMaterialStatus::Retired->value);self::assertSame('revoked',CredentialTrustKeyMaterialStatus::Revoked->value);}
public function testKeyMaterialKeepsOwnerValidityUsagesAndMetadataExplicit():void{$k=new CredentialTrustKeyMaterial('key-001','https://trust-anchor.example.test',CredentialTrustKeyMaterialStatus::Active,new DateTimeImmutable('2026-01-01T00:00:00Z'),new DateTimeImmutable('2027-01-01T00:00:00Z'),['credential-signing','metadata-signing'],['algorithm_family'=>'asymmetric']);self::assertSame('key-001',$k->keyId());self::assertSame('https://trust-anchor.example.test',$k->ownerEntityId());self::assertSame(['credential-signing','metadata-signing'],$k->usages());self::assertSame('asymmetric',$k->metadata()['algorithm_family']);}
public function testKeyLifecycleTransitionKeepsStatesTimeAndReasonExplicit():void{$at=new DateTimeImmutable('2026-08-12T03:00:00Z');$t=new CredentialTrustKeyLifecycleTransition(CredentialTrustKeyMaterialStatus::Active,CredentialTrustKeyMaterialStatus::Rotating,$at,'scheduled rotation');self::assertSame(CredentialTrustKeyMaterialStatus::Active,$t->from());self::assertSame(CredentialTrustKeyMaterialStatus::Rotating,$t->to());self::assertSame($at,$t->effectiveAt());self::assertSame('scheduled rotation',$t->reason());}
public function testAnchorAndKeyLifecycleContractsAreSeparated():void{foreach([CredentialTrustAnchorResolverInterface::class,CredentialTrustAnchorPolicyInterface::class,CredentialTrustKeyMaterialResolverInterface::class,CredentialTrustKeyLifecyclePolicyInterface::class] as $c){self::assertTrue((new \ReflectionClass($c))->isInterface());}}
public function testResolversExposeTypedResults():void{$a=new \ReflectionMethod(CredentialTrustAnchorResolverInterface::class,'resolve');$k=new \ReflectionMethod(CredentialTrustKeyMaterialResolverInterface::class,'resolve');self::assertSame('?'.CredentialTrustAnchor::class,(string)$a->getReturnType());self::assertSame('?'.CredentialTrustKeyMaterial::class,(string)$k->getReturnType());}
public function testArchitecturePreservesI1AndI2Contracts():void{foreach([\Sif\Foundation\Security\Contracts\CredentialTrustChainEvaluatorInterface::class,\Sif\Foundation\Security\Contracts\CredentialTrustRegistryResolverInterface::class,\Sif\Foundation\Security\Contracts\CredentialAccreditationResolverInterface::class] as $c){self::assertTrue(interface_exists($c),$c);}}
public function testAnchorAndKeyLifecycleLayerRemainsPkiJwksHsmKmsAndStorageNeutral():void{foreach([CredentialTrustAnchorResolverInterface::class,CredentialTrustAnchorPolicyInterface::class,CredentialTrustKeyMaterialResolverInterface::class,CredentialTrustKeyLifecyclePolicyInterface::class,CredentialTrustAnchor::class,CredentialTrustKeyMaterial::class,CredentialTrustKeyLifecycleTransition::class] as $c){$r=new \ReflectionClass($c);$s=file_get_contents((string)$r->getFileName());self::assertIsString($s);self::assertStringNotContainsString('PDO',$s);self::assertStringNotContainsString('Redis',$s);self::assertStringNotContainsString('curl_',strtolower($s));self::assertStringNotContainsString('Guzzle',$s);self::assertStringNotContainsString('openssl_',strtolower($s));self::assertStringNotContainsString('jwks',strtolower($s));self::assertStringNotContainsString('hsm',strtolower($s));self::assertStringNotContainsString('kms',strtolower($s));}}
}
