<?php

declare(strict_types=1);

namespace Sif\Builder\Generator\ReferenceReport;

final class ReferenceReportMarkdownRenderer
{
    public function render(ReferenceReportView $view): string
    {
        $lines = [
            '<!-- Generated by SIF Builder: reference.report. Do not edit manually. -->',
            '',
            '# Repository Reference Report',
            '',
            '## Summary',
            '',
            '| Metric | Value |',
            '|---|---:|',
            sprintf('| Documents | %d |', $view->totalDocuments),
            sprintf('| References | %d |', $view->totalReferences),
            sprintf('| Resolved | %d |', $view->resolvedReferences),
            sprintf('| Broken | %d |', $view->brokenReferences),
            sprintf('| Isolated documents | %d |', count($view->isolatedDocuments())),
            '',
            '## References by Type',
            '',
        ];

        if ($view->byType === []) {
            $lines[] = '_No references found._';
        } else {
            $lines[] = '| Type | Count |';
            $lines[] = '|---|---:|';
            foreach ($view->byType as $type => $count) {
                $lines[] = sprintf('| %s | %d |', $this->escape($type), $count);
            }
        }

        $lines[] = '';
        $lines[] = '## Broken References';
        $lines[] = '';
        if ($view->broken === []) {
            $lines[] = '_No broken references._';
        } else {
            $lines[] = '| Source | Target | Type | Line | Reason |';
            $lines[] = '|---|---|---|---:|---|';
            foreach ($view->broken as $reference) {
                $lines[] = sprintf(
                    '| `%s` | `%s` | %s | %s | %s |',
                    $this->escape($reference->source),
                    $this->escape($reference->target),
                    $this->escape($reference->type),
                    $reference->line === null ? '—' : (string) $reference->line,
                    $this->escape($reference->reason ?? 'unknown'),
                );
            }
        }

        $lines[] = '';
        $lines[] = '## Most Referenced Documents';
        $lines[] = '';
        $ranked = $view->mostReferencedDocuments();
        if ($ranked === []) {
            $lines[] = '_No incoming references found._';
        } else {
            $lines[] = '| Document | Type | Incoming | Outgoing | Broken outgoing |';
            $lines[] = '|---|---|---:|---:|---:|';
            foreach ($ranked as $document) {
                $lines[] = sprintf(
                    '| `%s` — %s | %s | %d | %d | %d |',
                    $this->escape($document->identifier),
                    $this->escape($document->title),
                    $this->escape($document->documentType),
                    $document->incoming,
                    $document->outgoing,
                    $document->brokenOutgoing,
                );
            }
        }

        $lines[] = '';
        $lines[] = '## Isolated Documents';
        $lines[] = '';
        $isolated = $view->isolatedDocuments();
        if ($isolated === []) {
            $lines[] = '_No isolated documents._';
        } else {
            foreach ($isolated as $document) {
                $lines[] = sprintf('- `%s` — %s', $this->escape($document->identifier), $this->escape($document->title));
            }
        }

        $lines[] = '';
        $lines[] = '## Resolved References';
        $lines[] = '';
        if ($view->resolved === []) {
            $lines[] = '_No resolved references._';
        } else {
            $lines[] = '| Source | Target | Type | Line |';
            $lines[] = '|---|---|---|---:|';
            foreach ($view->resolved as $reference) {
                $lines[] = sprintf(
                    '| `%s` | `%s` | %s | %s |',
                    $this->escape($reference->source),
                    $this->escape($reference->target),
                    $this->escape($reference->type),
                    $reference->line === null ? '—' : (string) $reference->line,
                );
            }
        }

        return implode("\n", $lines) . "\n";
    }

    private function escape(string $value): string
    {
        return str_replace(['\\', '|', "\r", "\n"], ['\\\\', '\\|', ' ', ' '], trim($value));
    }
}
