<?php

declare(strict_types=1);

namespace Sif\Builder\Generator\DocumentationNavigation;

final readonly class DocumentationNavigationMarkdownRenderer
{
    public const GENERATED_MARKER = '<!-- Generated by SIF Builder: documentation.navigation. Do not edit manually. -->';

    public function render(DocumentationNavigationView $view): string
    {
        $lines = [
            self::GENERATED_MARKER,
            '',
            '# Engineering Documentation Navigation',
            '',
            sprintf('Governed documents: **%d**', $view->totalDocuments),
            '',
            '## Generated views',
            '',
            '- [Repository index](INDEX.generated.md)',
            '- [Reference report](REFERENCES.generated.md)',
            '- [Reference graph](../build/reference-graph.generated.json)',
            '- [Repository manifest](../build/repository-manifest.generated.json)',
            '',
            '## Documentation',
            '',
        ];

        if ($view->groups === []) {
            $lines[] = '_No governed documentation was indexed._';
            $lines[] = '';
            return implode("
", $lines);
        }

        foreach ($view->groups as $group) {
            $lines[] = sprintf('### %s', $this->inline($group->heading()));
            $lines[] = '';

            foreach ($group->entries as $entry) {
                $lines[] = sprintf(
                    '- [`%s`](%s) — %s _(type: %s; status: %s; version: %s)_',
                    $this->code($entry->identifier),
                    $entry->link,
                    $this->inline($entry->title),
                    $this->inline($entry->documentType),
                    $this->inline($entry->status),
                    $this->inline($entry->version),
                );
            }

            $lines[] = '';
        }

        return implode("
", $lines);
    }

    private function inline(string $value): string
    {
        return str_replace(["", "
"], [' ', ' '], trim($value));
    }

    private function code(string $value): string
    {
        return str_replace('`', '\`', trim($value));
    }
}
