<?php

declare(strict_types=1);

namespace Sif\Builder\Tests\Generator\ReferenceReport;

use PHPUnit\Framework\TestCase;
use Sif\Builder\Generator\ReferenceReport\DocumentReferenceView;
use Sif\Builder\Generator\ReferenceReport\ReferenceReportEntryView;
use Sif\Builder\Generator\ReferenceReport\ReferenceReportMarkdownRenderer;
use Sif\Builder\Generator\ReferenceReport\ReferenceReportView;

final class ReferenceReportMarkdownRendererTest extends TestCase
{
    public function testRendersStableMarkdownAndEscapesTableContent(): void
    {
        $view = new ReferenceReportView(
            totalDocuments: 2,
            totalReferences: 1,
            resolvedReferences: 0,
            brokenReferences: 1,
            resolved: [],
            broken: [new ReferenceReportEntryView('WP-105', 'SPEC-999', 'related', 'broken', 8, 'target|not_found')],
            documents: [new DocumentReferenceView('WP-105', 'Built-in | Generators', 'WP', 0, 0, 1)],
            byType: ['related' => 1],
        );

        $first = (new ReferenceReportMarkdownRenderer())->render($view);
        $second = (new ReferenceReportMarkdownRenderer())->render($view);

        self::assertSame($first, $second);
        self::assertStringContainsString('target\\|not_found', $first);
        self::assertStringContainsString('<!-- Generated by SIF Builder: reference.report.', $first);
    }
}
