@startuml

interface ContainerInterface
interface FactoryInterface

class Binding
enum BindingType
class ResolutionContext

ContainerInterface --> Binding
ContainerInterface --> BindingType
ContainerInterface --> ResolutionContext

FactoryInterface ..> ContainerInterface

@enduml