<?php

declare(strict_types=1);

namespace Sif\Builder\Generator\RepositoryIndex;

final class RepositoryIndexMarkdownRenderer
{
    public const GENERATED_MARKER = '<!-- Generated by SIF Builder: repository.index. Do not edit manually. -->';

    public function render(RepositoryIndexView $view): string
    {
        $lines = [
            self::GENERATED_MARKER,
            '',
            '# Engineering Repository Index',
            '',
            '## Summary',
            '',
            sprintf('- Total documents: %d', $view->totalDocuments),
            sprintf('- Resolved references: %d', $view->resolvedReferences),
            sprintf('- Unresolved references: %d', $view->unresolvedReferences),
            '',
        ];

        $this->appendCounts($lines, 'Documents by type', $view->byType);
        $this->appendCounts($lines, 'Documents by status', $view->byStatus);

        $lines[] = '## Documents';
        $lines[] = '';

        if ($view->sections === []) {
            $lines[] = '_No governed documents were indexed._';
            $lines[] = '';
        }

        foreach ($view->sections as $section) {
            $lines[] = sprintf('### %s', $this->escapeInline($section->documentType));
            $lines[] = '';
            $lines[] = '| Identifier | Title | Status | Version | Path |';
            $lines[] = '|---|---|---|---|---|';

            foreach ($section->entries as $entry) {
                $lines[] = sprintf(
                    '| %s | %s | %s | %s | [`%s`](%s) |',
                    $this->escapeCell($entry->identifier),
                    $this->escapeCell($entry->title),
                    $this->escapeCell($entry->status),
                    $this->escapeCell($entry->version),
                    $this->escapeCode($entry->path),
                    $entry->link,
                );
            }

            $lines[] = '';
        }

        if ($view->unresolvedReferences > 0) {
            $lines[] = '## Reference Health';
            $lines[] = '';
            $lines[] = sprintf(
                '> Warning: %d unresolved reference%s detected. Run the reference report generator for details.',
                $view->unresolvedReferences,
                $view->unresolvedReferences === 1 ? '' : 's',
            );
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /** @param list<string> $lines @param array<string, int> $counts */
    private function appendCounts(array &$lines, string $title, array $counts): void
    {
        $lines[] = sprintf('### %s', $title);
        $lines[] = '';
        if ($counts === []) {
            $lines[] = '- None';
        } else {
            foreach ($counts as $name => $count) {
                $lines[] = sprintf('- %s: %d', $this->escapeInline($name), $count);
            }
        }
        $lines[] = '';
    }

    private function escapeCell(string $value): string
    {
        return str_replace(["\r", "\n", '|'], [' ', ' ', '\\|'], trim($value));
    }

    private function escapeInline(string $value): string
    {
        return str_replace(["\r", "\n"], [' ', ' '], trim($value));
    }

    private function escapeCode(string $value): string
    {
        return str_replace('`', '\\`', $value);
    }
}
