<?php

declare(strict_types=1);

namespace Sif\Builder\Repository;

use RuntimeException;

final class MarkdownRepositoryIndexWriter implements RepositoryIndexWriterInterface
{
    public function write(
        RepositoryIndex $index,
        RepositoryStatistics $statistics,
        string $outputFile,
    ): void {
        if (trim($outputFile) === '') {
            throw new RuntimeException('Repository index output file must not be empty.');
        }

        $directory = dirname($outputFile);
        if (!is_dir($directory) && !mkdir($directory, 0777, true) && !is_dir($directory)) {
            throw new RuntimeException(sprintf('Unable to create repository index directory "%s".', $directory));
        }

        $content = $this->render($index, $statistics);
        $temporaryFile = $outputFile . '.tmp';

        if (file_put_contents($temporaryFile, $content, LOCK_EX) === false) {
            throw new RuntimeException(sprintf('Unable to write repository index "%s".', $temporaryFile));
        }

        if (!rename($temporaryFile, $outputFile)) {
            @unlink($temporaryFile);

            throw new RuntimeException(sprintf('Unable to replace repository index "%s".', $outputFile));
        }
    }

    public function render(RepositoryIndex $index, RepositoryStatistics $statistics): string
    {
        $lines = [
            '# Engineering Repository Index',
            '',
            '> Generated automatically by SIF Builder. Do not edit this file manually.',
            '',
            '## Summary',
            '',
            sprintf('- Total documents: %d', $statistics->total),
            '',
        ];

        $this->appendStatistics($lines, 'Documents by category', $statistics->byCategory);
        $this->appendStatistics($lines, 'Documents by status', $statistics->byStatus);
        $this->appendStatistics($lines, 'Documents by class', $statistics->byDocumentClass);
        $this->appendStatistics($lines, 'Documents by work package', $statistics->byWorkPackage);

        $lines[] = '## Documents';
        $lines[] = '';
        $lines[] = '| Identifier | Title | Class | Category | Status | Version | Work Package | Path |';
        $lines[] = '|---|---|---|---|---|---|---|---|';

        foreach ($index->all() as $entry) {
            $lines[] = sprintf(
                '| %s | %s | %s | %s | %s | %s | %s | `%s` |',
                $this->escapeCell($entry->identifier),
                $this->escapeCell($entry->title),
                $this->escapeCell($entry->documentClass),
                $this->escapeCell($entry->category),
                $this->escapeCell($entry->status),
                $this->escapeCell($entry->version),
                $this->escapeCell($entry->workPackage ?? '—'),
                $this->escapeCode($this->normalizePath($entry->path)),
            );
        }

        if ($index->isEmpty()) {
            $lines[] = '| — | No documents indexed | — | — | — | — | — | — |';
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * @param list<string> $lines
     * @param array<string, int> $counts
     */
    private function appendStatistics(array &$lines, string $title, array $counts): void
    {
        $lines[] = sprintf('### %s', $title);
        $lines[] = '';

        if ($counts === []) {
            $lines[] = '- None';
        } else {
            foreach ($counts as $name => $count) {
                $lines[] = sprintf('- %s: %d', $this->escapeInline($name), $count);
            }
        }

        $lines[] = '';
    }

    private function escapeCell(string $value): string
    {
        return str_replace(["\r", "\n", '|'], [' ', ' ', '\\|'], trim($value));
    }

    private function escapeInline(string $value): string
    {
        return str_replace(["\r", "\n"], [' ', ' '], trim($value));
    }

    private function escapeCode(string $value): string
    {
        return str_replace('`', '\\`', $value);
    }

    private function normalizePath(string $path): string
    {
        return str_replace('\\', '/', $path);
    }
}
